--user TABLE
CREATE TABLE FRIENDLIST (
	FRIENDLISTID SERIAL PRIMARY KEY,
    USERID INT REFERENCES PALUSER(USERID),
	FRIENDID INT REFERENCES PALUSER(USERID),
	FRIENDLISTTIME TIMESTAMP
);

--SAMPLE iNSERT
INSERT INTO FRIENDLIST (USERID, FRIENDID,FRIENDLISTTIME)VALUES (
'4',
'5',
TIMESTAMP '1997-01-31 09:26:50.12');


--DROP Method
DROP TABLE FRIENDLIST;