--user TABLE
CREATE TABLE PALUSER (
        USERID SERIAL PRIMARY KEY,
	USERNAME  VARCHAR(20) NOT NULL,
	PASSWORD  VARCHAR(20) NOT NULL,
	CURRENTPOSITION GEOMETRY(Point, 4326),
	LASTUPDATETIME TIMESTAMP
);

--creating index
CREATE INDEX PALUSER_gix
  ON PALUSER 
  USING GIST (CURRENTPOSITION); 

--SAMPLE iNSERT
INSERT INTO PALUSER (USERNAME , PASSWORD, CURRENTPOSITION, LASTUPDATETIME)VALUES (
'suleyman',
'qwerty',
ST_GeomFromText('POINT(-39.312312 168.2132131)', 4326),
TIMESTAMP '1997-01-31 09:26:50.12');

--DROP Method
DROP INDEX PALUSER_gix;
DROP TABLE PALUSER;