-- PATHPOINTS TABLE
CREATE TABLE PATHPOINTS (
    PATHID  SERIAL PRIMARY KEY,
	USERID 	INT REFERENCES PALUSER(USERID),
	PATHCREATETIME TIMESTAMP,
	PATHCOORDINATES GEOMETRY(Point, 4326)
);

--creating index
CREATE INDEX PATHPOINTS_gix
  ON PATHPOINTS
  USING GIST (PATHCOORDINATES); 

--SAMPLE iNSERT point
INSERT INTO PATHPOINTS ( USERID, PATHCREATETIME, PATHCOORDINATES) VALUES (
'2',
TIMESTAMP '1997-01-31 09:26:50.12',
ST_GeomFromText('POINT(-39.312312 168.2132131)', 4326)
);




--DROP Method
DROP INDEX PATHPOINTS_gix;
DROP TABLE PATHPOINTS;